#import <Foundation/Foundation.h>
#import "SWGUser.h"
#import "SWGApi.h"

/**
* StrafesNET Public API
* ### How to use To request an api key open a support request in the [issue tracker](https://issues.strafes.net/client/index.php#/types/3/issues).  ### Default API request rate limits are as follows * 100 requests per minute * 3000 requests per hour  ### Game IDs ``` 1 Bhop 2 Surf ``` ### Style IDs ``` 1 Autohop 2 Scroll 3 Sideways 4 Half-Sideways 5 W-Only 6 A-Only 7 Backwards ``` 
*
* OpenAPI spec version: 1.0.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/



@interface SWGUserApi: NSObject <SWGApi>

extern NSString* kSWGUserApiErrorDomain;
extern NSInteger kSWGUserApiMissingParamErrorCode;

-(instancetype) initWithApiClient:(SWGApiClient *)apiClient NS_DESIGNATED_INITIALIZER;

/// 
/// User from id.
///
/// @param userId User ID filter
/// 
///  code:200 message:"Expected response to a valid request",
///  code:0 message:"unexpected error"
///
/// @return SWGUser*
-(NSURLSessionTask*) userUserIdGetWithUserId: (NSNumber*) userId
    completionHandler: (void (^)(SWGUser* output, NSError* error)) handler;



@end
