--[[
  StrafesNET Public API
 
  ### How to use To request an api key open a support request in the [issue tracker](https://issues.strafes.net/client/index.php#/types/3/issues).  ### Default API request rate limits are as follows * 100 requests per minute * 3000 requests per hour  ### Game IDs ``` 1 Bhop 2 Surf ``` ### Style IDs ``` 1 Autohop 2 Scroll 3 Sideways 4 Half-Sideways 5 W-Only 6 A-Only 7 Backwards ``` 
 
  OpenAPI spec version: 1.0.0
  
  Generated by: https://github.com/swagger-api/swagger-codegen.git
]]

-- map class
local map = {}
local map_mt = {
	__name = "map";
	__index = map;
}

local function cast_map(t)
	return setmetatable(t, map_mt)
end

local function new_map(ID, display_name, creator, game, date, play_count)
	return cast_map({
		["ID"] = ID;
		["DisplayName"] = display_name;
		["Creator"] = creator;
		["Game"] = game;
		["Date"] = date;
		["PlayCount"] = play_count;
	})
end

return {
	cast = cast_map;
	new = new_map;
}
