/**
 * StrafesNET Public API
 * ### How to use To request an api key open a support request in the [issue tracker](https://issues.strafes.net/client/index.php#/types/3/issues).  ### Default API request rate limits are as follows * 100 requests per minute * 3000 requests per hour  ### Game IDs ``` 1 Bhop 2 Surf ``` ### Style IDs ``` 1 Autohop 2 Scroll 3 Sideways 4 Half-Sideways 5 W-Only 6 A-Only 7 Backwards ``` 
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator 2.4.21.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */



#include "Time.h"

namespace io {
namespace swagger {
namespace client {
namespace model {

Time::Time()
{
    m_ID = 0;
    m_IDIsSet = false;
    m_Time = 0;
    m_TimeIsSet = false;
    m_User = 0;
    m_UserIsSet = false;
    m_Map = 0;
    m_MapIsSet = false;
    m_Date = 0;
    m_DateIsSet = false;
    m_Style = 0;
    m_StyleIsSet = false;
    m_Mode = 0;
    m_ModeIsSet = false;
    m_Game = 0;
    m_GameIsSet = false;
}

Time::~Time()
{
}

void Time::validate()
{
    // TODO: implement validation
}

web::json::value Time::toJson() const
{
    web::json::value val = web::json::value::object();

    if(m_IDIsSet)
    {
        val[utility::conversions::to_string_t("ID")] = ModelBase::toJson(m_ID);
    }
    if(m_TimeIsSet)
    {
        val[utility::conversions::to_string_t("Time")] = ModelBase::toJson(m_Time);
    }
    if(m_UserIsSet)
    {
        val[utility::conversions::to_string_t("User")] = ModelBase::toJson(m_User);
    }
    if(m_MapIsSet)
    {
        val[utility::conversions::to_string_t("Map")] = ModelBase::toJson(m_Map);
    }
    if(m_DateIsSet)
    {
        val[utility::conversions::to_string_t("Date")] = ModelBase::toJson(m_Date);
    }
    if(m_StyleIsSet)
    {
        val[utility::conversions::to_string_t("Style")] = ModelBase::toJson(m_Style);
    }
    if(m_ModeIsSet)
    {
        val[utility::conversions::to_string_t("Mode")] = ModelBase::toJson(m_Mode);
    }
    if(m_GameIsSet)
    {
        val[utility::conversions::to_string_t("Game")] = ModelBase::toJson(m_Game);
    }

    return val;
}

void Time::fromJson(web::json::value& val)
{
    if(val.has_field(utility::conversions::to_string_t("ID")))
    {
        web::json::value& fieldValue = val[utility::conversions::to_string_t("ID")];
        if(!fieldValue.is_null())
        {
            setID(ModelBase::int32_tFromJson(fieldValue));
        }
    }
    if(val.has_field(utility::conversions::to_string_t("Time")))
    {
        web::json::value& fieldValue = val[utility::conversions::to_string_t("Time")];
        if(!fieldValue.is_null())
        {
            setTime(ModelBase::int32_tFromJson(fieldValue));
        }
    }
    if(val.has_field(utility::conversions::to_string_t("User")))
    {
        web::json::value& fieldValue = val[utility::conversions::to_string_t("User")];
        if(!fieldValue.is_null())
        {
            setUser(ModelBase::int32_tFromJson(fieldValue));
        }
    }
    if(val.has_field(utility::conversions::to_string_t("Map")))
    {
        web::json::value& fieldValue = val[utility::conversions::to_string_t("Map")];
        if(!fieldValue.is_null())
        {
            setMap(ModelBase::int32_tFromJson(fieldValue));
        }
    }
    if(val.has_field(utility::conversions::to_string_t("Date")))
    {
        web::json::value& fieldValue = val[utility::conversions::to_string_t("Date")];
        if(!fieldValue.is_null())
        {
            setDate(ModelBase::int32_tFromJson(fieldValue));
        }
    }
    if(val.has_field(utility::conversions::to_string_t("Style")))
    {
        web::json::value& fieldValue = val[utility::conversions::to_string_t("Style")];
        if(!fieldValue.is_null())
        {
            setStyle(ModelBase::int32_tFromJson(fieldValue));
        }
    }
    if(val.has_field(utility::conversions::to_string_t("Mode")))
    {
        web::json::value& fieldValue = val[utility::conversions::to_string_t("Mode")];
        if(!fieldValue.is_null())
        {
            setMode(ModelBase::int32_tFromJson(fieldValue));
        }
    }
    if(val.has_field(utility::conversions::to_string_t("Game")))
    {
        web::json::value& fieldValue = val[utility::conversions::to_string_t("Game")];
        if(!fieldValue.is_null())
        {
            setGame(ModelBase::int32_tFromJson(fieldValue));
        }
    }
}

void Time::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t("."))
    {
        namePrefix += utility::conversions::to_string_t(".");
    }

    if(m_IDIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t("ID"), m_ID));
    }
    if(m_TimeIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t("Time"), m_Time));
    }
    if(m_UserIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t("User"), m_User));
    }
    if(m_MapIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t("Map"), m_Map));
    }
    if(m_DateIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t("Date"), m_Date));
    }
    if(m_StyleIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t("Style"), m_Style));
    }
    if(m_ModeIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t("Mode"), m_Mode));
    }
    if(m_GameIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t("Game"), m_Game));
    }
}

void Time::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t("."))
    {
        namePrefix += utility::conversions::to_string_t(".");
    }

    if(multipart->hasContent(utility::conversions::to_string_t("ID")))
    {
        setID(ModelBase::int32_tFromHttpContent(multipart->getContent(utility::conversions::to_string_t("ID"))));
    }
    if(multipart->hasContent(utility::conversions::to_string_t("Time")))
    {
        setTime(ModelBase::int32_tFromHttpContent(multipart->getContent(utility::conversions::to_string_t("Time"))));
    }
    if(multipart->hasContent(utility::conversions::to_string_t("User")))
    {
        setUser(ModelBase::int32_tFromHttpContent(multipart->getContent(utility::conversions::to_string_t("User"))));
    }
    if(multipart->hasContent(utility::conversions::to_string_t("Map")))
    {
        setMap(ModelBase::int32_tFromHttpContent(multipart->getContent(utility::conversions::to_string_t("Map"))));
    }
    if(multipart->hasContent(utility::conversions::to_string_t("Date")))
    {
        setDate(ModelBase::int32_tFromHttpContent(multipart->getContent(utility::conversions::to_string_t("Date"))));
    }
    if(multipart->hasContent(utility::conversions::to_string_t("Style")))
    {
        setStyle(ModelBase::int32_tFromHttpContent(multipart->getContent(utility::conversions::to_string_t("Style"))));
    }
    if(multipart->hasContent(utility::conversions::to_string_t("Mode")))
    {
        setMode(ModelBase::int32_tFromHttpContent(multipart->getContent(utility::conversions::to_string_t("Mode"))));
    }
    if(multipart->hasContent(utility::conversions::to_string_t("Game")))
    {
        setGame(ModelBase::int32_tFromHttpContent(multipart->getContent(utility::conversions::to_string_t("Game"))));
    }
}

int32_t Time::getID() const
{
    return m_ID;
}


void Time::setID(int32_t value)
{
    m_ID = value;
    m_IDIsSet = true;
}
bool Time::iDIsSet() const
{
    return m_IDIsSet;
}

void Time::unsetID()
{
    m_IDIsSet = false;
}

int32_t Time::getTime() const
{
    return m_Time;
}


void Time::setTime(int32_t value)
{
    m_Time = value;
    m_TimeIsSet = true;
}
bool Time::timeIsSet() const
{
    return m_TimeIsSet;
}

void Time::unsetTime()
{
    m_TimeIsSet = false;
}

int32_t Time::getUser() const
{
    return m_User;
}


void Time::setUser(int32_t value)
{
    m_User = value;
    m_UserIsSet = true;
}
bool Time::userIsSet() const
{
    return m_UserIsSet;
}

void Time::unsetUser()
{
    m_UserIsSet = false;
}

int32_t Time::getMap() const
{
    return m_Map;
}


void Time::setMap(int32_t value)
{
    m_Map = value;
    m_MapIsSet = true;
}
bool Time::mapIsSet() const
{
    return m_MapIsSet;
}

void Time::unsetMap()
{
    m_MapIsSet = false;
}

int32_t Time::getDate() const
{
    return m_Date;
}


void Time::setDate(int32_t value)
{
    m_Date = value;
    m_DateIsSet = true;
}
bool Time::dateIsSet() const
{
    return m_DateIsSet;
}

void Time::unsetDate()
{
    m_DateIsSet = false;
}

int32_t Time::getStyle() const
{
    return m_Style;
}


void Time::setStyle(int32_t value)
{
    m_Style = value;
    m_StyleIsSet = true;
}
bool Time::styleIsSet() const
{
    return m_StyleIsSet;
}

void Time::unsetStyle()
{
    m_StyleIsSet = false;
}

int32_t Time::getMode() const
{
    return m_Mode;
}


void Time::setMode(int32_t value)
{
    m_Mode = value;
    m_ModeIsSet = true;
}
bool Time::modeIsSet() const
{
    return m_ModeIsSet;
}

void Time::unsetMode()
{
    m_ModeIsSet = false;
}

int32_t Time::getGame() const
{
    return m_Game;
}


void Time::setGame(int32_t value)
{
    m_Game = value;
    m_GameIsSet = true;
}
bool Time::gameIsSet() const
{
    return m_GameIsSet;
}

void Time::unsetGame()
{
    m_GameIsSet = false;
}

}
}
}
}

