/*
 * StrafesNET Public API
 * ### How to use To request an api key open a support request in the [issue tracker](https://issues.strafes.net/client/index.php#/types/3/issues).  ### Default API request rate limits are as follows * 100 requests per minute * 3000 requests per hour  ### Game IDs ``` 1 Bhop 2 Surf ``` ### Style IDs ``` 1 Autohop 2 Scroll 3 Sideways 4 Half-Sideways 5 W-Only 6 A-Only 7 Backwards ``` 
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.Rank;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for RankApi
 */
@Ignore
public class RankApiTest {

    private final RankApi api = new RankApi();

    
    /**
     * 
     *
     * Top ranked players, paged at 50 per page.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void rankGetTest() throws ApiException {
        Integer style = null;
        Integer game = null;
        Integer page = null;
        List<Rank> response = api.rankGet(style, game, page);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * Get rank of user by their id.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void rankUserIdGetTest() throws ApiException {
        Integer userId = null;
        Integer style = null;
        Integer game = null;
        Rank response = api.rankUserIdGet(userId, style, game);

        // TODO: test validations
    }
    
}
